//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procedure_has_relatedprocedure
    {
        public int Procedure_has_RelatedProcedurecol { get; set; }
        public int ProcedureID { get; set; }
        public int RelatedProcedureID { get; set; }
    
        public virtual procedure procedure { get; set; }
        public virtual procedure procedure1 { get; set; }
    }
}
